version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "VpcId=\"vpc-048049e25f0424ea2\" LambdaSubnet1=\"subnet-0aaf4cf447ebba581\" LambdaSubnet2=\"subnet-00d0e5a5a15e030de\" RDSProxyName=\"example-proxy\" RDSProxyEndpoint=\"example-proxy.proxy-c28uub7r2j68.ap-northeast-1.rds.amazonaws.com\" RDSSecretName=\"db-credentials-default\" DBSecretArn=\"arn:aws:secretsmanager:ap-northeast-1:165985788939:secret:db-credentials-default-UjPykP\" DBName=\"example\" LambdaSecurityGroup=\"sg-0f651b077a63ae4af\""
image_repositories = []
