AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User CRUD Application

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  LambdaSubnet1:
    Type: AWS::EC2::Subnet::Id
  LambdaSubnet2:
    Type: AWS::EC2::Subnet::Id
  DBProxyEndpoint:
    Type: String
  DBSecretArn:
    Type: String
  DBName:
    Type: String
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: app/
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref LambdaSubnet1
          - !Ref LambdaSubnet2
      Events:
        UserAPI:
          Type: Api
          Properties:
            Path: /user
            Method: ANY
            RestApiId:
              Ref: UserApi
        InitializeAPI:
          Type: Api
          Properties:
            Path: /initialize
            Method: POST
            RestApiId:
              Ref: UserApi
      Environment:
        Variables:
          DB_PROXY_ENDPOINT: !Ref DBProxyEndpoint
          DB_SECRET_ARN: !Ref DBSecretArn
          DB_NAME: !Ref DBName
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DBSecretArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
          - index.ts
        Banner:
          - js=import { createRequire } from 'module';const require = createRequire(import.meta.url);



Outputs:
  UserApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"