AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User CRUD Application

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Handler: index.handler
    Environment:
      Variables:
        POWERTOOLS_LOG_LEVEL: INFO
        POWERTOOLS_SERVICE_NAME: rds-example

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  LambdaSubnet1:
    Type: AWS::EC2::Subnet::Id
  LambdaSubnet2:
    Type: AWS::EC2::Subnet::Id
  RDSProxyName:
    Type: String
  RDSProxyEndpoint:
    Type: String
  RDSSecretName:
    Type: String
  DBSecretArn:
    Type: String
  DBName:
    Type: String
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: app/
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref LambdaSubnet1
          - !Ref LambdaSubnet2
      Events:
        UserAPI:
          Type: Api
          Properties:
            Path: /user
            Method: ANY
            RestApiId:
              Ref: UserApi
        InitializeAPI:
          Type: Api
          Properties:
            Path: /initialize
            Method: POST
            RestApiId:
              Ref: UserApi
      Environment:
        Variables:
          RDS_PROXY_NAME: !Ref RDSProxyName
          RDS_PROXY_ENDPOINT: !Ref RDSProxyEndpoint
          RDS_SECRET_NAME: !Ref RDSSecretName
          DB_NAME: !Ref DBName
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - rds:DescribeDBProxies
            Resource: '*'
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DBSecretArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - index.ts
        Banner:
          - js=import { createRequire } from 'module';const require = createRequire(import.meta.url);



Outputs:
  UserApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"